# Form implementation generated from reading ui file 'display/origin_files/mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWebEngineWidgets import QWebEngineView

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 461)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabTutorial = QtWidgets.QWidget()
        self.tabTutorial.setObjectName("tabTutorial")
        self.gridLayout = QtWidgets.QGridLayout(self.tabTutorial)
        self.gridLayout.setObjectName("gridLayout")
        self.gboxTutorialButtons = QtWidgets.QGroupBox(self.tabTutorial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gboxTutorialButtons.sizePolicy().hasHeightForWidth())
        self.gboxTutorialButtons.setSizePolicy(sizePolicy)
        self.gboxTutorialButtons.setTitle("")
        self.gboxTutorialButtons.setObjectName("gboxTutorialButtons")
        self.layTutorial = QtWidgets.QVBoxLayout(self.gboxTutorialButtons)
        self.layTutorial.setObjectName("layTutorial")
        self.gridLayout.addWidget(self.gboxTutorialButtons, 0, 0, 1, 1)
        self.vtextTutorialInfo = QWebEngineView(self.tabTutorial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtextTutorialInfo.sizePolicy().hasHeightForWidth())
        self.vtextTutorialInfo.setSizePolicy(sizePolicy)
        self.vtextTutorialInfo.setObjectName("vtextTutorialInfo")
        self.gridLayout.addWidget(self.vtextTutorialInfo, 0, 1, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 351, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabTutorial, "")
        self.tabExamples = QtWidgets.QWidget()
        self.tabExamples.setObjectName("tabExamples")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabExamples)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gboxExamplesButtons = QtWidgets.QGroupBox(self.tabExamples)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gboxExamplesButtons.sizePolicy().hasHeightForWidth())
        self.gboxExamplesButtons.setSizePolicy(sizePolicy)
        self.gboxExamplesButtons.setTitle("")
        self.gboxExamplesButtons.setObjectName("gboxExamplesButtons")
        self.layExample = QtWidgets.QVBoxLayout(self.gboxExamplesButtons)
        self.layExample.setObjectName("layExample")
        self.gridLayout_2.addWidget(self.gboxExamplesButtons, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 303, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.btnRunTest = QtWidgets.QPushButton(self.tabExamples)
        self.btnRunTest.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.btnRunTest.setObjectName("btnRunTest")
        self.gridLayout_2.addWidget(self.btnRunTest, 2, 0, 1, 1)
        self.vtextExampleInfo = QWebEngineView(self.tabExamples)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtextExampleInfo.sizePolicy().hasHeightForWidth())
        self.vtextExampleInfo.setSizePolicy(sizePolicy)
        self.vtextExampleInfo.setObjectName("vtextExampleInfo")
        self.gridLayout_2.addWidget(self.vtextExampleInfo, 0, 1, 3, 1)
        self.tabWidget.addTab(self.tabExamples, "")
        self.tabAbout = QtWidgets.QWidget()
        self.tabAbout.setObjectName("tabAbout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabAbout)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.tabAbout)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_4.addWidget(self.textBrowser)
        self.lblAboutAuthor = QtWidgets.QLabel(self.tabAbout)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblAboutAuthor.setFont(font)
        self.lblAboutAuthor.setText("")
        self.lblAboutAuthor.setObjectName("lblAboutAuthor")
        self.verticalLayout_4.addWidget(self.lblAboutAuthor)
        self.tabWidget.addTab(self.tabAbout, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Дипломный проект"))
        self.vtextTutorialInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTutorial), _translate("MainWindow", "Теория"))
        self.btnRunTest.setText(_translate("MainWindow", "Перейти к тесту"))
        self.vtextExampleInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExamples), _translate("MainWindow", "Практика"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAbout), _translate("MainWindow", "Справка"))
