# Form implementation generated from reading ui file 'origin_files/testWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(536, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        self.btnAnswThree = QtWidgets.QPushButton(Form)
        self.btnAnswThree.setText("")
        self.btnAnswThree.setObjectName("btnAnswThree")
        self.gridLayout.addWidget(self.btnAnswThree, 5, 2, 1, 1)
        self.lblTimer = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTimer.sizePolicy().hasHeightForWidth())
        self.lblTimer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.lblTimer.setFont(font)
        self.lblTimer.setObjectName("lblTimer")
        self.gridLayout.addWidget(self.lblTimer, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.btnBack = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBack.sizePolicy().hasHeightForWidth())
        self.btnBack.setSizePolicy(sizePolicy)
        self.btnBack.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.btnBack.setObjectName("btnBack")
        self.gridLayout.addWidget(self.btnBack, 0, 3, 1, 1)
        self.btnAnswFour = QtWidgets.QPushButton(Form)
        self.btnAnswFour.setText("")
        self.btnAnswFour.setObjectName("btnAnswFour")
        self.gridLayout.addWidget(self.btnAnswFour, 6, 2, 1, 1)
        self.btnAnswTwo = QtWidgets.QPushButton(Form)
        self.btnAnswTwo.setText("")
        self.btnAnswTwo.setObjectName("btnAnswTwo")
        self.gridLayout.addWidget(self.btnAnswTwo, 4, 2, 1, 1)
        self.btnAnswOne = QtWidgets.QPushButton(Form)
        self.btnAnswOne.setText("")
        self.btnAnswOne.setObjectName("btnAnswOne")
        self.gridLayout.addWidget(self.btnAnswOne, 3, 2, 1, 1)
        self.lblTestText = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblTestText.setFont(font)
        self.lblTestText.setText("")
        self.lblTestText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTestText.setObjectName("lblTestText")
        self.gridLayout.addWidget(self.lblTestText, 0, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Тест"))
        self.lblTimer.setText(_translate("Form", "00:00:00"))
        self.btnBack.setText(_translate("Form", "НАЗАД"))
